services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in the Render dashboard
      - key: FRONTEND_URL
        sync: false  # Set this manually or define it here directly

    plan: free  # Change to 'starter' or higher if needed
    autoDeploy: true
